import { describe, expect, it } from "vitest";
import { renderSprite, renderModule } from "../../scripts/gen-sprites";
import { PALETTE, SPRITE_MAPS, type SpriteName } from "../sprites/maps";
import { SPRITES } from "../sprites/generated";

const names = Object.keys(SPRITE_MAPS) as SpriteName[];

describe("sprite pipeline", () => {
  it("committed generated.ts is in sync with maps.ts (run `npm run sprites`)", () => {
    for (const name of names) {
      expect(SPRITES[name], `sprite "${name}" is stale`).toBe(renderSprite(SPRITE_MAPS[name]));
    }
    expect(Object.keys(SPRITES).sort()).toEqual([...names].sort());
  });

  it("emits crispEdges SVG with palette colors only", () => {
    const palette = new Set(Object.values(PALETTE));
    for (const name of names) {
      const svg = renderSprite(SPRITE_MAPS[name]);
      expect(svg).toContain('shape-rendering="crispEdges"');
      expect(svg).toContain('class="spr"');
      expect(svg).toContain('aria-hidden="true"');
      const fills = [...svg.matchAll(/fill="([^"]+)"/g)].map((m) => m[1]!);
      expect(fills.length).toBeGreaterThan(0);
      for (const f of fills) expect(palette.has(f), `${name}: non-palette fill ${f}`).toBe(true);
    }
  });

  it("run-length encodes horizontal pixel runs into single rects", () => {
    const svg = renderSprite(["ppp.", ".k.."]);
    expect(svg).toContain('<rect x="0" y="0" width="3" height="1" fill="#be185d"/>');
    expect(svg).toContain('<rect x="1" y="1" width="1" height="1" fill="#18181b"/>');
    expect([...svg.matchAll(/<rect/g)].length).toBe(2);
    expect(svg).toContain('viewBox="0 0 4 2"');
  });

  it("rejects unknown palette chars and ragged rows", () => {
    expect(() => renderSprite(["xx"])).toThrow(/unknown palette char/);
    expect(() => renderSprite(["pp", "p"])).toThrow(/width/);
  });

  it("renderModule emits the committed header and all sprites", () => {
    const mod = renderModule();
    expect(mod).toContain("GENERATED by scripts/gen-sprites.ts");
    for (const name of names) expect(mod).toContain(`${name}:`);
  });
});
