/**
 * watersort/logic.ts — pure Water Sort rules. No DOM, no storage; rand is
 * injected. Levels are generated by REVERSE-POURING from a solved state
 * with each reverse step exactly invertible, so every generated level is
 * solvable by construction (tech-design risk note).
 */

export type Rand = () => number;

/** A tube is a stack of color ids, bottom → top. */
export type Tube = string[];

export const CAP = 4;
export const EMPTY_TUBES = 2;

/** Palette color ids (rendered by the UI; palette hexes stay in CSS). */
export const WS_COLORS = ["pink", "green", "ink", "rose", "wine", "sage", "slate"] as const;

export interface TopSegment {
  color: string;
  size: number;
}

export function topSegment(tube: Tube): TopSegment | null {
  const top = tube[tube.length - 1];
  if (top === undefined) return null;
  let size = 0;
  for (let i = tube.length - 1; i >= 0 && tube[i] === top; i--) size++;
  return { color: top, size };
}

/** A pour is legal if source has liquid, dest has space, and colors match. */
export function canPour(from: Tube, to: Tube): boolean {
  const seg = topSegment(from);
  if (!seg) return false;
  if (to.length >= CAP) return false;
  const toTop = to[to.length - 1];
  return toTop === undefined || toTop === seg.color;
}

/**
 * Pour tube i → j: moves as much of the top same-color segment as fits.
 * Returns the new tube array (immutable) or null if illegal.
 */
export function pour(tubes: Tube[], i: number, j: number): Tube[] | null {
  const from = tubes[i];
  const to = tubes[j];
  if (i === j || !from || !to || !canPour(from, to)) return null;
  const seg = topSegment(from);
  if (!seg) return null;
  const n = Math.min(seg.size, CAP - to.length);
  const next = tubes.map((t) => [...t]);
  const nf = next[i];
  const nt = next[j];
  if (!nf || !nt) return null;
  for (let k = 0; k < n; k++) {
    const c = nf.pop();
    if (c !== undefined) nt.push(c);
  }
  return next;
}

/** Solved: every tube is empty or a full single-color stack. */
export function isSolved(tubes: Tube[]): boolean {
  return tubes.every(
    (t) => t.length === 0 || (t.length === CAP && t.every((c) => c === t[0])),
  );
}

export interface WsLevel {
  tubes: Tube[];
  /** A forward solution (pour [from, to] pairs) — proof of solvability. */
  solution: [number, number][];
}

/**
 * Generate a level with `colors` colors (+2 empty tubes) by reverse-pouring
 * from the solved state. Each reverse move (take k of the top color c from
 * X, drop on Y) is constrained so the inverse pour Y→X is exactly legal:
 *   - X keeps c on top (k < segment) or empties entirely (k == X length)
 *   - Y is empty or NOT topped with c (no segment merging), with space ≥ k
 * Reversing the move list therefore replays back to solved.
 */
export function generate(colors: number, rand: Rand, steps?: number): WsLevel {
  const n = Math.min(colors, WS_COLORS.length);
  const total = steps ?? n * 8;

  for (let attempt = 0; attempt < 8; attempt++) {
    const tubes: Tube[] = [];
    for (let c = 0; c < n; c++) tubes.push(Array<string>(CAP).fill(WS_COLORS[c] ?? "pink"));
    for (let e = 0; e < EMPTY_TUBES; e++) tubes.push([]);
    const reverse: [number, number][] = [];

    for (let s = 0; s < total; s++) {
      const options: [number, number, number][] = []; // [from, to, k]
      for (let x = 0; x < tubes.length; x++) {
        const tx = tubes[x];
        if (!tx) continue;
        const seg = topSegment(tx);
        if (!seg) continue;
        for (let y = 0; y < tubes.length; y++) {
          if (y === x) continue;
          const ty = tubes[y];
          if (!ty) continue;
          const space = CAP - ty.length;
          if (space <= 0) continue;
          const yTop = ty[ty.length - 1];
          if (yTop !== undefined && yTop === seg.color) continue; // no merging
          const maxK = Math.min(seg.size, space);
          for (let k = 1; k <= maxK; k++) {
            if (k < seg.size || k === tx.length) options.push([x, y, k]);
          }
        }
      }
      if (options.length === 0) break;
      const pick = options[Math.floor(rand() * options.length)];
      if (!pick) break;
      const [x, y, k] = pick;
      const tx = tubes[x];
      const ty = tubes[y];
      if (!tx || !ty) break;
      for (let m = 0; m < k; m++) {
        const c = tx.pop();
        if (c !== undefined) ty.push(c);
      }
      reverse.push([x, y]);
    }

    if (!isSolved(tubes)) {
      // forward solution = inverse moves in reverse order
      const solution: [number, number][] = reverse
        .map(([x, y]): [number, number] => [y, x])
        .reverse();
      return { tubes, solution };
    }
  }
  // pathological rand (e.g. constant) — return a trivially mixed level
  const tubes: Tube[] = [];
  for (let c = 0; c < n; c++) tubes.push(Array<string>(CAP).fill(WS_COLORS[c] ?? "pink"));
  for (let e = 0; e < EMPTY_TUBES; e++) tubes.push([]);
  const a = tubes[0];
  const b = tubes[n];
  if (a && b) {
    const c = a.pop();
    if (c !== undefined) b.push(c);
  }
  return { tubes, solution: [[n, 0]] };
}

/** Snapshot-based undo stack (UI keeps one per level). */
export interface UndoStack {
  push(tubes: Tube[]): void;
  pop(): Tube[] | null;
  size(): number;
  clear(): void;
}

export function createUndo(limit = 64): UndoStack {
  let stack: Tube[][] = [];
  return {
    push(tubes) {
      stack.push(tubes.map((t) => [...t]));
      if (stack.length > limit) stack.shift();
    },
    pop() {
      const s = stack.pop();
      return s ? s.map((t) => [...t]) : null;
    },
    size: () => stack.length,
    clear() {
      stack = [];
    },
  };
}
