/**
 * logic.ts — pure Lights Out rules (no DOM). Unit-tested.
 *
 * 5×5 board, flat boolean array, true = lit. A press toggles the cell and
 * its orthogonal neighbors; the goal is all lights out. Boards are
 * generated by pressing random cells on a solved board — since each press
 * is its own inverse, every generated board is solvable by replaying the
 * scramble presses.
 */

export const SIZE = 5;
export const CELLS = SIZE * SIZE;

export type LoBoard = boolean[];

/** Toggle cell i and its orthogonal neighbors. Returns a new board. */
export function press(b: readonly boolean[], i: number): LoBoard {
  const out = [...b];
  const r = Math.floor(i / SIZE);
  const c = i % SIZE;
  const flip = (rr: number, cc: number): void => {
    if (rr >= 0 && rr < SIZE && cc >= 0 && cc < SIZE) {
      const j = rr * SIZE + cc;
      out[j] = !out[j];
    }
  };
  flip(r, c);
  flip(r - 1, c);
  flip(r + 1, c);
  flip(r, c - 1);
  flip(r, c + 1);
  return out;
}

/** Solved = every light off. */
export const isSolved = (b: readonly boolean[]): boolean => b.every((v) => !v);

export interface Generated {
  board: LoBoard;
  /** The scramble presses — replaying them solves the board. */
  presses: number[];
}

/**
 * Scramble a solved board with `count` random presses (retrying the rare
 * all-off outcome with one extra press). Always solvable by construction.
 */
export function generate(count = 8, rand: () => number = Math.random): Generated {
  let board: LoBoard = Array<boolean>(CELLS).fill(false);
  const presses: number[] = [];
  for (let n = 0; n < count; n++) {
    const i = Math.floor(rand() * CELLS);
    presses.push(i);
    board = press(board, i);
  }
  while (isSolved(board)) {
    const i = Math.floor(rand() * CELLS);
    presses.push(i);
    board = press(board, i);
  }
  return { board, presses };
}
