/**
 * gen-sprites.ts — ASCII pixel maps → src/sprites/generated.ts (ADR-5).
 *
 * Run with `npm run sprites` (plain `node` — Node 24 strips types natively).
 * Each row is run-length encoded into one <rect> per horizontal run of
 * same-colored pixels, exactly like the mockup's build.py output:
 * crispEdges SVG, palette colors only, no image assets.
 *
 * The output module is COMMITTED so the site builds without this script.
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";
import { PALETTE, SPRITE_MAPS, type SpriteRows } from "../src/sprites/maps.ts";

/** Render one ASCII map to a crispEdges SVG string (mockup format). */
export function renderSprite(rows: SpriteRows): string {
  const h = rows.length;
  const w = rows[0]?.length ?? 0;
  const rects: string[] = [];

  rows.forEach((row, y) => {
    if (row.length !== w) throw new Error(`row ${y} width ${row.length} != ${w}`);
    let x = 0;
    while (x < w) {
      const ch = row[x]!;
      if (ch === ".") {
        x++;
        continue;
      }
      const fill = PALETTE[ch];
      if (!fill) throw new Error(`unknown palette char "${ch}" at ${x},${y}`);
      let run = 1;
      while (x + run < w && row[x + run] === ch) run++;
      rects.push(`<rect x="${x}" y="${y}" width="${run}" height="1" fill="${fill}"/>`);
      x += run;
    }
  });

  return (
    `<svg class="spr" viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg" ` +
    `shape-rendering="crispEdges" aria-hidden="true">${rects.join("")}</svg>`
  );
}

/** Render the full generated.ts module source. */
export function renderModule(): string {
  const entries = (Object.keys(SPRITE_MAPS) as (keyof typeof SPRITE_MAPS)[])
    .map((name) => `  ${name}:\n    '${renderSprite(SPRITE_MAPS[name])}',`)
    .join("\n");
  return `/* eslint-disable */
// ============================================================
// GENERATED by scripts/gen-sprites.ts — DO NOT EDIT.
// Regenerate with \`npm run sprites\` after changing maps.ts.
// ============================================================

/** Inline crispEdges SVG strings (build-time constants — safe for innerHTML). */
export const SPRITES = {
${entries}
} as const;

export type SpriteName = keyof typeof SPRITES;
`;
}

function main(): void {
  const out = resolve(fileURLToPath(new URL(".", import.meta.url)), "../src/sprites/generated.ts");
  writeFileSync(out, renderModule());
  console.log(`gen-sprites: wrote ${out}`);
}

// run only when executed directly (not when imported by tests)
const invoked = process.argv[1];
if (invoked && resolve(invoked) === fileURLToPath(import.meta.url)) main();
